export enum CacheTag {
  AdminUsers = 'admin-users',
  AuthUser = 'auth-user',
  AuthUserStatus = 'auth-user-status',
  Certificates = 'certificates',
  Course = 'course',
  Courses = 'courses',
  DocCategories = 'doc-categories',
  Notifications = 'notifications',
  Organizations = 'organizations',
  SkillGroups = 'skill-groups',
  TeamMembers = 'team-members',
  User = 'user',
  UserEmail = 'user-email',
}
