name: Setup
description: Set up the environment for the project.

runs:
  using: composite
  steps:
    - uses: actions/cache@v4
      with:
        path: .turbo
        key: ${{ runner.os }}-turbo-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-turbo-
    - uses: pnpm/action-setup@v4
      with:
        run_install: false
    - uses: actions/setup-node@v4
      with:
        node-version-file: .node-version
        cache: pnpm
    - name: Install dependencies
      shell: sh
      run: |
        pnpm install --frozen-lockfile --strict-peer-dependencies
        echo ./node_modules/.bin >> $GITHUB_PATH
    - name: Build packages
      shell: sh
      run: pnpm build --filter @glore/*
