import releaseItConfig from '@repo/release-it-config'

export default releaseItConfig({
  autoReleaseNotes: false,
  bumpFiles: ['apps/*/config/metadata.json', 'apps/*/package.json'],
  // Run checks only if there are unpushed commits
  afterInit: '[ -n "$(git log @{u}.. 2>/dev/null)" ] && (pnpm build && pnpm check) || exit 0',
  // Format autogenerated files
  afterBump: 'pnpm run lint:fix && git add .',
  afterRelease:
    'echo v${version} released and scheduled for deployment: https://github.com/${repo.repository}/deployments/Production',
})
