packages:
  - apps/*
  - packages/*

catalog:
  '@types/node': 24.3.1
  dotenv: ^17.2.2
  eslint: ^9.35.0
  prettier: ^3.6.2
  prettier-plugin-sql: ^0.19.2
  release-it: ^19.0.4
  shellcheck: ^4.1.0
  tsup: ^8.5.0
  typescript: ^5.9.2

dangerouslyAllowAllBuilds: false

ignoredBuiltDependencies:
  - '@prisma/engines'
  - '@tailwindcss/oxide'
  - esbuild
  - msgpackr-extract
  - msw
  - sharp
  - unrs-resolver

onlyBuiltDependencies:
  - '@vercel/speed-insights'
  - supabase
