packages:
  - apps/*
  - packages/*
  - packages/dev/*

catalog:
  '@types/node': 24.6.1
  '@types/react': ^19.1.16
  '@types/react-dom': ^19.1.9
  class-variance-authority: ^0.7.1
  deepmerge-ts: ^7.1.5
  dotenv: ^17.2.3
  eslint: ^9.36.0
  lucide-react: ^0.544.0
  motion: ^12.23.22
  prettier: ^3.6.2
  react: ^19.1.1
  react-dom: ^19.1.1
  react-hook-form: ^7.63.0
  release-it: ^19.0.5
  shellcheck: ^4.1.0
  sonner: ^2.0.7
  tailwindcss: ^4.1.13
  tsup: ^8.5.0
  typescript: ^5.9.3
  uploadthing: ^7.7.4
  zod: ^4.1.11

dangerouslyAllowAllBuilds: false

ignoredBuiltDependencies:
  - '@prisma/engines'
  - '@tailwindcss/oxide'
  - deno
  - esbuild
  - msgpackr-extract
  - msw
  - sharp
  - unrs-resolver

onlyBuiltDependencies:
  - '@vercel/speed-insights'
  - supabase
