packages:
  - apps/*
  - packages/*

catalog:
  '@biomejs/biome': 2.3.5
  '@types/node': ^24.10.1
  next: ^16.0.3
  typescript: ^5.9.3

dangerouslyAllowAllBuilds: false

ignoredBuiltDependencies:
  - deno
  - esbuild
  - msgpackr-extract
  - msw
  - sharp

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - '@vercel/speed-insights'
  - supabase
