packages:
  - apps/*
  - packages/*

catalog:
  '@biomejs/biome': ^2.3.2
  '@types/node': ^24.9.1
  next: ^16.0.0
  typescript: ^5.9.3

dangerouslyAllowAllBuilds: false

ignoredBuiltDependencies:
  - deno
  - esbuild
  - msgpackr-extract
  - msw
  - sharp

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - '@vercel/speed-insights'
  - supabase
