packages:
  - apps/*
  - packages/*

catalog:
  '@biomejs/biome': 2.3.8
  '@types/node': ^24.10.2
  next: ^16.0.8
  supabase: ^2.65.7
  typescript: ^5.9.3

dangerouslyAllowAllBuilds: false

ignoredBuiltDependencies:
  - '@tailwindcss/oxide'
  - deno
  - esbuild
  - msgpackr-extract
  - msw
  - sharp

onlyBuiltDependencies:
  - '@vercel/speed-insights'
  - supabase
