packages:
  - apps/*
  - packages/*

catalog:
  '@supabase/supabase-js': 2.55.0
  '@types/node': ^24.7.2
  '@types/react': ^19.2.2
  '@types/react-dom': ^19.2.2
  class-variance-authority: ^0.7.1
  next-intl: ^4.3.12
  react: ^19.2.0
  react-dom: ^19.2.0
  tailwind-merge: ^3.3.1
  typescript: ^5.9.3
  zod: ^4.1.12

dangerouslyAllowAllBuilds: false

ignoredBuiltDependencies:
  - esbuild
  - deno
  - msgpackr-extract
  - sharp

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - '@vercel/speed-insights'
  - supabase
