import { defineConfig } from 'vite-plus'

export default defineConfig({
  resolve: {
    tsconfigPaths: true,
  },
  staged: {
    '*': 'vp check --fix',
  },
  fmt: {
    ignorePatterns: ['*.d.ts', 'AGENTS.md', '.agents/**'],
    arrowParens: 'avoid',
    semi: false,
    singleQuote: true,
    trailingComma: 'es5',
    sortPackageJson: false,
    sortImports: {
      groups: [
        ['side_effect', 'side_effect_style', 'style'],
        'builtin',
        'react',
        'external',
        'internal',
        ['index', 'sibling', 'parent'],
        'unknown',
      ],
      customGroups: [
        {
          groupName: 'react',
          elementNamePattern: ['react', 'react/**', 'next', 'next/**'],
        },
      ],
      internalPattern: ['~/', '@/'],
      sortSideEffects: true,
      newlinesBetween: true,
    },
    sortTailwindcss: {
      stylesheet: './src/app/globals.css',
      functions: ['clsx', 'cn', 'cva'],
    },
    overrides: [
      {
        files: ['**/*.jsonc'],
        options: {
          trailingComma: 'none',
        },
      },
    ],
  },
  lint: {
    categories: {
      correctness: 'error',
      nursery: 'allow',
      pedantic: 'error',
      perf: 'error',
      restriction: 'allow',
      style: 'error',
      suspicious: 'error',
    },
    env: {
      browser: true,
      node: true,
      'shared-node-browser': true,
      es2024: true,
    },
    options: {
      typeAware: true,
      typeCheck: false,
      reportUnusedDisableDirectives: 'error',
      denyWarnings: true,
    },
    plugins: ['import', 'jsdoc', 'jsx-a11y', 'nextjs', 'node', 'promise', 'react', 'react-perf'],
    settings: {
      next: {
        rootDir: '.',
      },
      jsdoc: {
        augmentsExtendsReplacesDocs: false,
        exemptDestructuredRootsFromChecks: false,
        ignoreInternal: false,
        ignorePrivate: false,
        ignoreReplacesDocs: true,
        implementsReplacesDocs: false,
        overrideReplacesDocs: true,
        tagNamePreference: {},
      },
    },
    jsPlugins: [
      {
        name: 'react-doctor',
        specifier: 'react-doctor/oxlint-plugin',
      },
    ],
    rules: {
      curly: ['error', 'multi-line'],
      'func-style': ['error', 'expression'],
      'max-statements': ['error', 100],
      'no-ternary': 'off',
      'no-unused-vars': 'error',
      'sort-imports': [
        'error',
        {
          ignoreDeclarationSort: true,
        },
      ],
      'eslint/arrow-body-style': ['error', 'as-needed'],
      'eslint/capitalized-comments': 'off',
      'eslint/eqeqeq': 'error',
      'eslint/func-style': 'off',
      'eslint/id-length': 'off',
      'eslint/init-declarations': 'off',
      'eslint/max-depth': ['error', 5],
      'eslint/max-lines': 'off',
      'eslint/max-lines-per-function': 'off',
      'eslint/new-cap': 'off',
      'eslint/no-await-in-loop': 'off',
      'eslint/no-cond-assign': 'error',
      'eslint/no-console': [
        'warn',
        {
          allow: ['info', 'warn', 'error'],
        },
      ],
      'eslint/no-const-assign': 'error',
      'eslint/no-continue': 'off',
      'eslint/no-debugger': 'error',
      'eslint/no-dupe-keys': 'error',
      'eslint/no-duplicate-case': 'error',
      'eslint/no-duplicate-imports': 'off',
      'eslint/no-else-return': 'error',
      'eslint/no-empty-pattern': 'error',
      'eslint/no-eval': 'error',
      'eslint/no-extend-native': 'error',
      'eslint/no-extra-boolean-cast': 'error',
      'eslint/no-implicit-coercion': 'off',
      'eslint/no-inline-comments': 'off',
      'eslint/no-iterator': 'error',
      'eslint/no-label-var': 'error',
      'eslint/no-magic-numbers': 'off',
      'eslint/no-nested-ternary': 'off',
      'eslint/no-new-func': 'error',
      'eslint/no-new-native-nonconstructor': 'error',
      'eslint/no-param-reassign': 'warn',
      'eslint/no-promise-executor-return': 'off',
      'eslint/no-proto': 'error',
      'eslint/no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['../**'],
              message: 'Parent imports are not allowed, use an alias instead.',
            },
          ],
          paths: [
            {
              name: 'next/headers',
              importNames: ['cookies'],
              message: 'Import from @/actions/cookies instead.',
            },
          ],
        },
      ],
      'eslint/no-script-url': 'error',
      'eslint/no-self-compare': 'error',
      'eslint/no-shadow': 'error',
      'eslint/no-throw-literal': 'error',
      'eslint/no-unreachable': 'error',
      'eslint/no-unused-expressions': 'error',
      'eslint/no-unused-vars': [
        'error',
        {
          args: 'after-used',
          argsIgnorePattern: '^_',
          ignoreRestSiblings: true,
          vars: 'all',
          varsIgnorePattern: '^_',
        },
      ],
      'eslint/no-useless-catch': 'error',
      'eslint/no-useless-concat': 'error',
      'eslint/no-useless-constructor': 'error',
      'eslint/no-useless-rename': 'error',
      'eslint/no-var': 'error',
      'eslint/no-void': 'off',
      'eslint/no-warning-comments': 'off',
      'eslint/no-with': 'error',
      'eslint/operator-assignment': 'error',
      'eslint/prefer-const': 'error',
      'eslint/prefer-destructuring': 'off',
      'eslint/prefer-promise-reject-errors': 'warn',
      'eslint/prefer-template': 'error',
      'eslint/radix': 'error',
      'eslint/require-await': 'error',
      'eslint/sort-keys': 'off',
      'eslint/symbol-description': 'warn',
      'eslint/use-isnan': 'error',
      'eslint/valid-typeof': 'error',
      'import/consistent-type-specifier-style': ['error', 'prefer-inline'],
      'import/exports-last': 'off',
      'import/group-exports': 'off',
      'import/max-dependencies': 'off',
      'import/no-absolute-path': 'error',
      'import/no-anonymous-default-export': 'error',
      'import/no-commonjs': 'error',
      'import/no-cycle': 'error',
      'import/no-duplicates': 'error',
      'import/no-named-as-default': 'off',
      'import/no-named-export': 'off',
      'import/no-namespace': 'off',
      'import/no-nodejs-modules': 'off',
      'import/no-relative-parent-imports': 'error',
      'import/no-self-import': 'error',
      'import/no-unassigned-import': 'off',
      'import/no-webpack-loader-syntax': 'error',
      'import/prefer-default-export': 'off',
      'jsdoc/require-param': 'off',
      'jsdoc/require-returns': 'off',
      'jsx-a11y/alt-text': 'error',
      'jsx-a11y/anchor-has-content': 'warn',
      'jsx-a11y/anchor-is-valid': 'warn',
      'jsx-a11y/aria-props': 'error',
      'jsx-a11y/aria-role': 'error',
      'jsx-a11y/click-events-have-key-events': 'allow',
      'jsx-a11y/html-has-lang': 'error',
      'jsx-a11y/lang': 'error',
      'jsx-a11y/media-has-caption': 'allow',
      'jsx-a11y/no-autofocus': 'allow',
      'jsx-a11y/no-noninteractive-tabindex': 'allow',
      'jsx-a11y/no-static-element-interactions': 'allow',
      'jsx-a11y/scope': 'error',
      'jsx-a11y/tabindex-no-positive': 'error',
      'oxc/no-accumulating-spread': 'warn',
      'promise/always-return': 'error',
      'promise/avoid-new': 'off',
      'promise/catch-or-return': 'error',
      'promise/no-nesting': 'warn',
      'promise/prefer-await-to-callbacks': 'off',
      'promise/prefer-await-to-then': 'error',
      'react/jsx-curly-brace-presence': [
        'error',
        {
          children: 'always',
          propElementValues: 'always',
          props: 'never',
        },
      ],
      'react/display-name': 'off',
      'react/exhaustive-deps': 'error',
      'react/hook-use-state': 'off',
      'react/iframe-missing-sandbox': 'warn',
      'react/jsx-fragments': ['error', 'syntax'],
      'react/jsx-handler-names': 'off',
      'react/jsx-key': 'error',
      'react/jsx-max-depth': 'off',
      'react/jsx-no-constructed-context-values': 'off',
      'react/jsx-no-target-blank': 'error',
      'react/jsx-no-useless-fragment': 'off',
      'react/jsx-props-no-spreading': 'off',
      'react/no-array-index-key': 'allow',
      'react/no-children-prop': 'error',
      'react/no-danger': 'allow',
      'react/no-danger-with-children': 'error',
      'react/no-direct-mutation-state': 'error',
      'react/no-string-refs': 'error',
      'react/no-unescaped-entities': 'error',
      'react/react-in-jsx-scope': 'off',
      'react/rules-of-hooks': 'error',
      'react/self-closing-comp': 'error',
      'react/void-dom-elements-no-children': 'error',
      'react-doctor/advanced-event-handler-refs': 'error',
      'react-doctor/async-await-in-loop': 'error',
      'react-doctor/async-defer-await': 'error',
      'react-doctor/async-parallel': 'error',
      'react-doctor/client-localstorage-no-version': 'error',
      'react-doctor/client-passive-event-listeners': 'error',
      'react-doctor/design-no-bold-heading': 'error',
      'react-doctor/design-no-default-tailwind-palette': 'error',
      'react-doctor/design-no-em-dash-in-jsx-text': 'error',
      'react-doctor/design-no-redundant-padding-axes': 'error',
      'react-doctor/design-no-redundant-size-axes': 'error',
      'react-doctor/design-no-space-on-flex-children': 'off',
      'react-doctor/design-no-three-period-ellipsis': 'error',
      'react-doctor/design-no-vague-button-label': 'error',
      'react-doctor/effect-needs-cleanup': 'error',
      'react-doctor/js-batch-dom-css': 'error',
      'react-doctor/js-cache-property-access': 'error',
      'react-doctor/js-cache-storage': 'error',
      'react-doctor/js-combine-iterations': 'error',
      'react-doctor/js-early-exit': 'error',
      'react-doctor/js-flatmap-filter': 'error',
      'react-doctor/js-hoist-intl': 'off',
      'react-doctor/js-hoist-regexp': 'error',
      'react-doctor/js-index-maps': 'error',
      'react-doctor/js-length-check-first': 'error',
      'react-doctor/js-min-max-loop': 'error',
      'react-doctor/js-set-map-lookups': 'error',
      'react-doctor/js-tosorted-immutable': 'error',
      'react-doctor/nextjs-async-client-component': 'error',
      'react-doctor/nextjs-image-missing-sizes': 'error',
      'react-doctor/nextjs-inline-script-missing-id': 'error',
      'react-doctor/nextjs-missing-metadata': 'error',
      'react-doctor/nextjs-no-a-element': 'error',
      'react-doctor/nextjs-no-client-fetch-for-server-data': 'error',
      'react-doctor/nextjs-no-client-side-redirect': 'error',
      'react-doctor/nextjs-no-css-link': 'error',
      'react-doctor/nextjs-no-font-link': 'error',
      'react-doctor/nextjs-no-head-import': 'error',
      'react-doctor/nextjs-no-img-element': 'error',
      'react-doctor/nextjs-no-native-script': 'error',
      'react-doctor/nextjs-no-polyfill-script': 'error',
      'react-doctor/nextjs-no-redirect-in-try-catch': 'error',
      'react-doctor/nextjs-no-side-effect-in-get-handler': 'error',
      'react-doctor/nextjs-no-use-search-params-without-suspense': 'off',
      'react-doctor/no-array-index-as-key': 'error',
      'react-doctor/no-barrel-import': 'error',
      'react-doctor/no-cascading-set-state': 'off',
      'react-doctor/no-dark-mode-glow': 'error',
      'react-doctor/no-default-props': 'error',
      'react-doctor/no-derived-state-effect': 'error',
      'react-doctor/no-derived-useState': 'off',
      'react-doctor/no-direct-state-mutation': 'error',
      'react-doctor/no-disabled-zoom': 'error',
      'react-doctor/no-document-start-view-transition': 'error',
      'react-doctor/no-dynamic-import-path': 'off',
      'react-doctor/no-effect-chain': 'error',
      'react-doctor/no-effect-event-handler': 'error',
      'react-doctor/no-effect-event-in-deps': 'error',
      'react-doctor/no-eval': 'error',
      'react-doctor/no-event-trigger-state': 'error',
      'react-doctor/no-fetch-in-effect': 'error',
      'react-doctor/no-flush-sync': 'error',
      'react-doctor/no-full-lodash-import': 'error',
      'react-doctor/no-generic-handler-names': 'error',
      'react-doctor/no-giant-component': 'off',
      'react-doctor/no-global-css-variable-animation': 'error',
      'react-doctor/no-gradient-text': 'error',
      'react-doctor/no-gray-on-colored-background': 'error',
      'react-doctor/no-inline-bounce-easing': 'error',
      'react-doctor/no-inline-exhaustive-style': 'error',
      'react-doctor/no-inline-prop-on-memo-component': 'error',
      'react-doctor/no-justified-text': 'error',
      'react-doctor/no-large-animated-blur': 'error',
      'react-doctor/no-layout-property-animation': 'error',
      'react-doctor/no-layout-transition-inline': 'error',
      'react-doctor/no-legacy-class-lifecycles': 'error',
      'react-doctor/no-legacy-context-api': 'error',
      'react-doctor/no-long-transition-duration': 'error',
      'react-doctor/no-many-boolean-props': 'error',
      'react-doctor/no-mirror-prop-effect': 'error',
      'react-doctor/no-moment': 'error',
      'react-doctor/no-mutable-in-deps': 'error',
      'react-doctor/no-nested-component-definition': 'error',
      'react-doctor/no-outline-none': 'error',
      'react-doctor/no-permanent-will-change': 'error',
      'react-doctor/no-polymorphic-children': 'error',
      'react-doctor/no-prevent-default': 'error',
      'react-doctor/no-prop-callback-in-effect': 'error',
      'react-doctor/no-pure-black-background': 'error',
      'react-doctor/no-react-dom-deprecated-apis': 'error',
      'react-doctor/no-react19-deprecated-apis': 'error',
      'react-doctor/no-render-in-render': 'error',
      'react-doctor/no-render-prop-children': 'error',
      'react-doctor/no-scale-from-zero': 'error',
      'react-doctor/no-secrets-in-client-code': 'error',
      'react-doctor/no-set-state-in-render': 'error',
      'react-doctor/no-side-tab-border': 'error',
      'react-doctor/no-tiny-text': 'error',
      'react-doctor/no-transition-all': 'error',
      'react-doctor/no-uncontrolled-input': 'error',
      'react-doctor/no-undeferred-third-party': 'error',
      'react-doctor/no-usememo-simple-expression': 'error',
      'react-doctor/no-wide-letter-spacing': 'error',
      'react-doctor/no-z-index-9999': 'error',
      'react-doctor/prefer-dynamic-import': 'error',
      'react-doctor/prefer-use-effect-event': 'error',
      'react-doctor/prefer-use-sync-external-store': 'error',
      'react-doctor/prefer-useReducer': 'off',
      'react-doctor/react-compiler-destructure-method': 'error',
      'react-doctor/rendering-animate-svg-wrapper': 'error',
      'react-doctor/rendering-conditional-render': 'error',
      'react-doctor/rendering-hoist-jsx': 'error',
      'react-doctor/rendering-hydration-mismatch-time': 'error',
      'react-doctor/rendering-hydration-no-flicker': 'error',
      'react-doctor/rendering-script-defer-async': 'error',
      'react-doctor/rendering-svg-precision': 'off',
      'react-doctor/rendering-usetransition-loading': 'error',
      'react-doctor/rerender-defer-reads-hook': 'error',
      'react-doctor/rerender-dependencies': 'error',
      'react-doctor/rerender-derived-state-from-hook': 'error',
      'react-doctor/rerender-functional-setstate': 'error',
      'react-doctor/rerender-lazy-state-init': 'error',
      'react-doctor/rerender-memo-before-early-return': 'error',
      'react-doctor/rerender-memo-with-default-value': 'error',
      'react-doctor/rerender-state-only-in-handlers': 'error',
      'react-doctor/rerender-transitions-scroll': 'error',
      'react-doctor/server-after-nonblocking': 'error',
      'react-doctor/server-auth-actions': 'error',
      'react-doctor/server-cache-with-object-literal': 'error',
      'react-doctor/server-dedup-props': 'error',
      'react-doctor/server-fetch-without-revalidate': 'error',
      'react-doctor/server-hoist-static-io': 'error',
      'react-doctor/server-no-mutable-module-state': 'error',
      'react-doctor/server-sequential-independent-await': 'error',
      'react-doctor/use-lazy-motion': 'off',
      'react-perf/jsx-no-new-array-as-prop': 'off',
      'react-perf/jsx-no-new-function-as-prop': 'off',
      'react-perf/jsx-no-jsx-as-prop': 'off',
      'react-perf/jsx-no-new-object-as-prop': 'off',
      'typescript/array-type': [
        'error',
        {
          default: 'array',
        },
      ],
      'typescript/ban-ts-comment': [
        'error',
        {
          'ts-check': false,
          'ts-expect-error': 'allow-with-description',
          'ts-ignore': true,
          'ts-nocheck': true,
        },
      ],
      'typescript/consistent-type-definitions': ['error', 'interface'],
      'typescript/consistent-type-imports': [
        'error',
        {
          fixStyle: 'inline-type-imports',
          prefer: 'type-imports',
        },
      ],
      'typescript/no-empty-interface': 'warn',
      'typescript/no-explicit-any': 'warn',
      'typescript/no-extra-non-null-assertion': 'error',
      'typescript/no-inferrable-types': 'error',
      'typescript/no-misused-new': 'error',
      'typescript/no-non-null-assertion': 'allow',
      'typescript/no-require-imports': 'error',
      'typescript/no-floating-promises': 'error',
      'typescript/no-misused-promises': 'error',
      'typescript/no-unnecessary-type-assertion': 'warn',
      'typescript/prefer-nullish-coalescing': 'warn',
      'typescript/prefer-optional-chain': 'warn',
      'unicorn/error-message': 'error',
      'unicorn/filename-case': [
        'error',
        {
          case: 'kebabCase',
          ignore: ['^\\$'],
        },
      ],
      'unicorn/new-for-builtins': 'error',
      'unicorn/no-array-for-each': 'error',
      'unicorn/no-instanceof-array': 'error',
      'unicorn/no-negated-condition': 'warn',
      'unicorn/no-unnecessary-await': 'warn',
      'unicorn/no-useless-promise-resolve-reject': 'warn',
      'unicorn/prefer-array-flat': 'warn',
      'unicorn/prefer-array-flat-map': 'warn',
      'unicorn/prefer-includes': 'warn',
      'unicorn/prefer-number-properties': 'warn',
      'unicorn/prefer-optional-catch-binding': 'warn',
      'unicorn/prefer-prototype-methods': 'warn',
      'unicorn/prefer-spread': 'warn',
      'unicorn/prefer-string-starts-ends-with': 'warn',
      'unicorn/prefer-string-trim-start-end': 'warn',
      'unicorn/prefer-structured-clone': 'warn',
      'unicorn/prefer-type-error': 'warn',
      'unicorn/throw-new-error': 'error',
    },
    overrides: [
      {
        files: ['*.config.ts'],
        rules: {
          'eslint/no-template-curly-in-string': 'off',
          'import/no-anonymous-default-export': 'off',
        },
      },
      {
        files: ['src/components/**/*.tsx'],
        rules: {
          'react-doctor/rendering-hydration-mismatch-time': 'off',
        },
      },
      {
        files: ['src/components/ui/**/*.tsx', 'src/components/blocks/**/*.tsx'],
        rules: {
          'nextjs/no-img-element': 'off',
          'react-doctor/nextjs-no-img-element': 'off',
          'react-doctor/no-generic-handler-names': 'off',
          'react-doctor/no-array-index-as-key': 'off',
        },
      },
      {
        files: ['src/app/\\[username\\]/page.tsx'],
        rules: {
          'react-doctor/server-sequential-independent-await': 'off',
        },
      },
      {
        files: ['src/emails/**'],
        rules: {
          'react-doctor/rendering-hydration-mismatch-time': 'off',
        },
      },
    ],
  },
})
