CREATE INDEX "accounts_user_id_idx" ON "accounts" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "assessments_lesson_id_idx" ON "assessments" USING btree ("lesson_id");--> statement-breakpoint
CREATE INDEX "evaluations_lesson_id_idx" ON "evaluations" USING btree ("lesson_id");--> statement-breakpoint
CREATE INDEX "question_options_question_id_idx" ON "question_options" USING btree ("question_id");--> statement-breakpoint
CREATE INDEX "questions_lesson_id_idx" ON "questions" USING btree ("lesson_id");--> statement-breakpoint
CREATE INDEX "certificate_skills_certificate_id_idx" ON "certificate_skills" USING btree ("certificate_id");--> statement-breakpoint
CREATE INDEX "certificate_skills_course_id_idx" ON "certificate_skills" USING btree ("course_id");--> statement-breakpoint
CREATE INDEX "certificates_user_id_idx" ON "certificates" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "certificates_organization_id_idx" ON "certificates" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "certificates_reviewer_id_idx" ON "certificates" USING btree ("reviewer_id");--> statement-breakpoint
CREATE INDEX "contributions_lesson_id_idx" ON "contributions" USING btree ("lesson_id");--> statement-breakpoint
CREATE INDEX "contributions_user_id_idx" ON "contributions" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "courses_skill_group_id_idx" ON "courses" USING btree ("skill_group_id");--> statement-breakpoint
CREATE INDEX "courses_creator_id_idx" ON "courses" USING btree ("creator_id");--> statement-breakpoint
CREATE INDEX "lessons_course_id_idx" ON "lessons" USING btree ("course_id");--> statement-breakpoint
CREATE INDEX "notifications_user_id_idx" ON "notifications" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "push_subscriptions_user_id_idx" ON "push_subscriptions" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "memberships_user_id_idx" ON "memberships" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "memberships_organization_id_idx" ON "memberships" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "org_join_requests_organization_id_idx" ON "organization_join_requests" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "org_join_requests_reviewed_by_idx" ON "organization_join_requests" USING btree ("reviewed_by");--> statement-breakpoint
CREATE INDEX "user_answers_user_id_idx" ON "user_answers" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "user_answers_option_id_idx" ON "user_answers" USING btree ("option_id");--> statement-breakpoint
CREATE INDEX "user_assessments_user_id_idx" ON "user_assessments" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "user_assessments_assessment_id_idx" ON "user_assessments" USING btree ("assessment_id");--> statement-breakpoint
CREATE INDEX "user_courses_user_id_idx" ON "user_courses" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "user_courses_course_id_idx" ON "user_courses" USING btree ("course_id");--> statement-breakpoint
CREATE INDEX "user_evaluations_user_id_idx" ON "user_evaluations" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "user_evaluations_evaluation_id_idx" ON "user_evaluations" USING btree ("evaluation_id");--> statement-breakpoint
CREATE INDEX "user_lessons_user_id_idx" ON "user_lessons" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "user_lessons_lesson_id_idx" ON "user_lessons" USING btree ("lesson_id");--> statement-breakpoint
CREATE INDEX "regions_coordinator_id_idx" ON "regions" USING btree ("coordinator_id");--> statement-breakpoint
CREATE INDEX "sessions_user_id_idx" ON "sessions" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "team_invitations_user_id_idx" ON "team_invitations" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "team_invitations_invited_by_idx" ON "team_invitations" USING btree ("invited_by");