name: Deploy
description: Rebases the environment-specific branch onto the default branch and triggers a deployment.

inputs:
  environment:
    description: The environment to deploy to, either `production` or `preview`.
    required: true
  ref:
    description: The branch to rebase onto, defaults to `main`.
    required: false
    default: main

runs:
  using: composite
  steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
        ref: ${{ inputs.environment }}
    - name: Rebase onto ${{ inputs.ref }}
      shell: sh
      run: |
        git fetch origin ${{ inputs.ref }}
        if ! git reset --hard origin/${{ inputs.ref }}; then
          echo "::error::Failed to rebase ${{ inputs.environment }} onto ${{ inputs.ref }}"
          exit 1
        fi
    - name: Push rebased branch
      shell: sh
      run: |
        if ! git push origin HEAD:${{ inputs.environment }} --force --no-verify; then
          echo "::error::Failed to push ${{ inputs.environment }} branch"
          exit 1
        fi
