blank_issues_enabled: false
contact_links:
  - name: Questions and discussion
    url: https://github.com/glorecertificate/glore/issues
    about: For general questions, search existing issues before opening a new one.
