name: Revert
description: Sets the remote database to a previous state by reverting the number of migrations specified.

inputs:
  migrations:
    description: Number of migrations to revert.
    required: true

runs:
  using: composite
  steps:
    - name: Set up environment
      uses: ./.github/actions/setup
      with:
        build: false
        dev-only: true
    - name: Revert database updates
      shell: sh
      run: glore db revert ${{ inputs.migrations }}
