export enum Route {
  Dashboard = '/',
  Login = '/login',
  Logout = '/logout',
  Signup = '/signup',
  ResetPassword = '/reset-password',
  Modules = '/modules',
  ModulesInProgress = '/modules/in-progress',
  ModulesNotStarted = '/modules/new',
  ModulesCompleted = '/modules/completed',
  ModulesAll = '/modules/all',
  Certificates = '/certificates',
  CertificatesMy = '/certificates/my',
  CertificatesUnderReview = '/certificates/under-review',
  CertificatesNew = '/certificates/new',
  CertificatesAll = '/certificates/all',
  Documentation = '/docs',
  DocumentationIntro = '/docs/intro',
  DocumentationGetStarted = '/docs/get-started',
  DocumentationTutorials = '/docs/tutorials',
  DocumentationChangelog = '/docs/changelog',
  // Projects = '/projects',
  Settings = '/settings',
  Profile = '/profile',
  Help = '/help',
}
