#!/usr/bin/env sh

SCHEMA=auth,public,storage
MIGRATIONS=supabase/migrations
file=$1

if [ -z "$file" ]; then
  echo "You must provide a migration name."
  exit 1
fi

./node_modules/.bin/supabase db diff --schema $SCHEMA --file "$file"
./node_modules/.bin/prettier --write $MIGRATIONS/*.sql
./node_modules/.bin/snaplet-seed sync
sh ./.bin/typegen 
