#!/usr/bin/env sh

SCHEMA=auth,public,storage
TYPES=supabase/types.ts
arg="--local"

[ -f .env ] && . ./.env

if [ -z "$SUPABASE_PROJECT_ID" ]; then
  echo "SUPABASE_PROJECT_ID is not set."
  exit 1
fi

if [ "$ENV" = "production" ] || [ "$NODE_ENV" = "production" ] || [ "$GITHUB_ACTIONS" = "true" ] || [ "$CI" = "true" ] || [ "$CI" = 1 ]; then
  arg="--project-id=$SUPABASE_PROJECT_ID"
fi

if ./node_modules/.bin/supabase gen types typescript --schema $SCHEMA "$arg" > $TYPES; then
  echo "Finished types generation."
fi
