#!/usr/bin/env sh
# shellcheck disable=SC2046

commitlint --from origin/main --to HEAD --verbose

# Root-level checks
tsc --noEmit
shellcheck $(find .husky -maxdepth 1 -type f)

# Project checks
pnpm build
pnpm check
