#!/usr/bin/env sh

OUTPUT_KEY="success"

[ -n "$GITHUB_OUTPUT" ] && exit 0

if [ -n "$nextRelease" ]; then
  output=$(echo "${OUTPUT_KEY}=true" || echo "${OUTPUT_KEY}=false") 
  echo "$output" >> "$GITHUB_OUTPUT"
  echo "Step output set to: $output"
fi
