#!/bin/sh

commit="$(cat "$(git rev-parse --show-toplevel)"/.git/COMMIT_EDITMSG)"

if [ -n "$(git status -s)" ]; then 
  echo "There are uncommitted changes. Please commit or stash them before pushing."
  exit 1
fi

commitlint --from origin/main --to HEAD --verbose
pnpm run typegen
pnpm run build
pnpm run check:fix

# Commit eventual fixes
[ -z "$(git status -s)" ] && exit 0
git reset --soft HEAD^
git add .
git commit -m "$commit" --no-verif

