name: CI

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:
  merge_group:
    types:
      - checks_requested

env:
  SUPABASE_TOKEN: ${{ secrets.SUPABASE_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  NEXT_TELEMETRY_DISABLED: 1
  TURBO_TELEMETRY_DISABLED: 1

jobs:
  code-checks:
    name: Code checks
    runs-on: ubuntu-latest
    env:
      SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL_PREVIEW }}
    permissions:
      checks: write
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@v5
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Run code checks
        uses: ./.github/actions/code-checks
