name: Deploy

on:
  push:
    branches:
      - main
    tags:
      - v*

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  deploy-preview:
    name: Deploy Preview
    if: "!startsWith(github.ref, 'refs/tags/')"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    environment:
      name: Preview
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: actions/setup-node@v6
        with:
          node-version-file: .node-version
          cache: pnpm
      - name: Install dependencies
        run: pnpm install -D --frozen-lockfile --ignore-scripts --strict-peer-dependencies
      - name: Deploy to Vercel
        run: ./node_modules/.bin/vercel deploy --token ${{ secrets.VERCEL_TOKEN }}

  deploy-prod:
    name: Deploy to Production
    if: "startsWith(github.ref, 'refs/tags/')"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    environment:
      name: Production
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: actions/setup-node@v6
        with:
          node-version-file: .node-version
          cache: pnpm
      - name: Install dependencies
        run: pnpm install -D --frozen-lockfile --ignore-scripts --strict-peer-dependencies
      - name: Deploy to Vercel
        run: ./node_modules/.bin/vercel deploy --prod --token ${{ secrets.VERCEL_TOKEN }}
