name: Release

on:
  push:
    tags:
      - v*

permissions:
  contents: read

jobs:
  release:
    name: Release
    permissions:
      contents: read
      deployments: write
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      environment: production
