name: Release

on:
  push:
    tags:
      - v*

jobs:
  check:
    name: Check
    permissions:
      contents: read
    uses: ./.github/workflows/check.yml
  deploy:
    name: Deploy
    permissions:
      contents: read
      deployments: write
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      environment: production
