name: Release

on:
  push:
    tags:
      - v*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  check:
    name: Check
    permissions:
      contents: read
    uses: ./.github/workflows/check.yml
  deploy:
    name: Deploy
    needs: check
    permissions:
      contents: read
      deployments: write
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      environment: production
